name: ProtocolSupportLegacySupport
main: protocolsupportlegacysupport.ProtocolSupportLegacySupport
version: 1.1
api-version: 1.13
author: _Shevchik_
load: STARTUP
depend: [ProtocolSupport, ProtocolLib]